name: Build TrashCat

on: [push, workflow_dispatch]
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: [self-hosted, Windows, product]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Debug Environment Variables
        shell: bash
        run: env
      - name: Test
        shell: bash
        run : echo $GITHUB_WORKSPACE
      - name: Build TrashCat
        shell: bash
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          echo $GITHUB_WORKSPACE
          "$UNITY_2021_3_HOME" -batchmode -stackTraceLogType None -projectPath $GITHUB_WORKSPACE/TrashCat -executeMethod BuildTrashCat.WindowsBuildFromCommandLine -logFile buildWindows.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildWindowsArtifact
          path: |
            **/TrashCat.exe
            **/*.log

  # build-macOS:
  #   runs-on: [self-hosted, MAC37]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: "recursive"

  #     - name: Build TrashCat
  #       run: |
  #         export ALTSERVER_PORT=13000
  #         export ALTSERVER_HOST="192.168.11.35"
  #         echo $CI_PROJECT_DIR
  #         $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/TrashCat -executeMethod BuildTrashCat.MacBuildFromCommandLine -logFile buildMac.log -quit

  #     - uses: actions/upload-artifact@v4
  #       if: always() # run this step even if one of the previous steps failed
  #       with:
  #         name: BuildMacArtifact
  #         path: |
  #           **/TrashCat.app
  #           **/*.log

  # build-android:
  #   runs-on: [self-hosted, MAC37]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: "recursive"

  #     - name: Build TrashCat
  #       run: |
  #         export ALTSERVER_PORT=13000
  #         export ALTSERVER_HOST="192.168.11.35"
  #         $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/TrashCat -executeMethod BuildTrashCat.AndroidBuildFromCommandLine -logFile buildAndroid.log -quit

  #     - uses: actions/upload-artifact@v4
  #       if: always() # run this step even if one of the previous steps failed
  #       with:
  #         name: BuildAndroidArtifact
  #         path: |
  #           **/TrashCat.apk
  #           **/*.log

  # build-iOS:
  #   runs-on: [self-hosted, MAC37]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: "recursive"

  #     - name: Build TrashCat
  #       run: |
  #         export ALTSERVER_PORT=13000
  #         export ALTSERVER_HOST="192.168.11.35"
  #         $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/TrashCat -executeMethod BuildTrashCat.IosBuildFromCommandLine -logFile buildiOS.log -quit

  #     - uses: actions/upload-artifact@v4
  #       if: always() # run this step even if one of the previous steps failed
  #       with:
  #         name: BuildiOSArtifact
  #         path: |
  #           **/TrashCat
  #           **/*.log

  # build-WebGL:
  #   runs-on: [self-hosted, MAC37]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: "recursive"

  #     - name: Build TrashCat
  #       run: |
  #         export ALTSERVER_PORT=13000
  #         export ALTSERVER_HOST="192.168.11.35"
  #         $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/TrashCat -executeMethod BuildTrashCat.WebGLBuildFromCommandLine -logFile buildWebGL.log -quit

  #     - uses: actions/upload-artifact@v4
  #       if: always() # run this step even if one of the previous steps failed
  #       with:
  #         name: BuildWebGLArtifact
  #         path: |
  #           **/build/webgl
  #           **/*.log